export interface CatalogItem {
  name: string;
  description: string;
  price: string;
  currency: string;
  category: string;
  durationMinutes: number | null;
  cities: string[];
  imageKeys: string[];
  promoLabel?: string;
}

export const SANTA_MARIA_CATALOG: CatalogItem[] = [
  {
    name: "Valoración o reserva",
    description: "Costo de valoración personalizada con nuestros especialistas. Aplicable a la cita.",
    price: "50000",
    currency: "COP",
    category: "consultas",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Botox por zona",
    description: "Tratamiento por zona individual: entrecejo, frente, orbicular de párpados, fox eyes o perfilamiento mandibular.",
    price: "630000",
    currency: "COP",
    category: "inyectables",
    durationMinutes: 20,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Full Face Botox",
    description: "Incluye todas las zonas: entrecejo, frente, orbicular, fox eyes y perfilamiento mandibular.",
    price: "1580000",
    currency: "COP",
    category: "inyectables",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Russian Lips",
    description: "Técnica de relleno de labios que busca un efecto más elevado y definido, con proyección del arco de cupido.",
    price: "820000",
    currency: "COP",
    category: "labios",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image6.jpeg", "image7.jpeg"],
  },
  {
    name: "Doll Lips",
    description: "Relleno de labios con volumen marcado, estilo muñeca. Mayor proyección y definición.",
    price: "1640000",
    currency: "COP",
    category: "labios",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image8.jpeg", "image9.jpeg", "image14.jpeg", "image15.jpeg"],
  },
  {
    name: "Red Lips",
    description: "Relleno de labios con ácido hialurónico, resultado natural y equilibrado.",
    price: "670000",
    currency: "COP",
    category: "labios",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image5.jpeg", "image10.jpeg", "image11.jpeg", "image12.jpeg"],
  },
  {
    name: "Full Face — Ácido Hialurónico",
    description: "Armonización facial completa con ácido hialurónico. Diseño facial personalizado para realzar tu belleza con resultados naturales.",
    price: "2999000",
    currency: "COP",
    category: "armonización",
    durationMinutes: 60,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image16.jpeg", "image28.jpeg"],
  },
  {
    name: "Full Face — Radiesse",
    description: "Bioestimulación completa con Radiesse. Estimula colágeno, redefine contorno y mejora la calidad de la piel.",
    price: "3999000",
    currency: "COP",
    category: "bioestimuladores",
    durationMinutes: 60,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image23.jpeg"],
  },
  {
    name: "Full Face — Sculptra",
    description: "Bioestimulación completa con Sculptra. Estimula producción natural de colágeno de forma progresiva.",
    price: "3999000",
    currency: "COP",
    category: "bioestimuladores",
    durationMinutes: 60,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: ["image24.jpeg"],
  },
  {
    name: "Radiesse (por vial)",
    description: "Bioestimulador que mejora la calidad de la piel, redefine contorno facial y estimula colágeno. Duración hasta 18 meses.",
    price: "2600000",
    currency: "COP",
    category: "bioestimuladores",
    durationMinutes: 45,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Sculptra (por vial)",
    description: "Bioestimulador facial que estimula la producción natural de colágeno. Resultados graduales y naturales.",
    price: "2500000",
    currency: "COP",
    category: "bioestimuladores",
    durationMinutes: 45,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Rinomodelación",
    description: "Procedimiento no quirúrgico con ácido hialurónico para perfilar el dorso nasal, levantar la punta y corregir asimetrías. Resultados inmediatos.",
    price: "820000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Marcación mandibular",
    description: "Perfilamiento del reborde mandibular con ácido hialurónico para definir el contorno del rostro.",
    price: "1640000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Proyección de mentón",
    description: "Proyección de mentón con ácido hialurónico para equilibrar el rostro y mejorar el perfil facial.",
    price: "820000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Proyección de pómulos",
    description: "Realce y definición de pómulos con ácido hialurónico (2 ml). Aporta volumen y soporte al rostro.",
    price: "1640000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Ojeras con ácido hialurónico",
    description: "Mejora la apariencia de ojeras, aporta hidratación, mejora pigmentación y disminuye bolsitas.",
    price: "820000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "NCTF — Ojeras",
    description: "Tratamiento enfocado en hidratar profundamente la piel y mejorar la pigmentación de la ojera.",
    price: "630000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Nasolabiales con AH",
    description: "Suaviza las líneas que van desde la nariz hacia la comisura de los labios con ácido hialurónico.",
    price: "820000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Lipopapada enzimática",
    description: "Reducción de grasa localizada en papada con enzimas Liporah. Incluye 2 aplicaciones. Requiere faja mentonera 21 noches.",
    price: "368000",
    currency: "COP",
    category: "facial",
    durationMinutes: 20,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Bichectomía enzimática",
    description: "Reducción de grasa en bolsas de Bichat con enzimas para afinar el contorno facial.",
    price: "368000",
    currency: "COP",
    category: "facial",
    durationMinutes: 20,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Hialuronidasa",
    description: "Retiro de ácido hialurónico en labios para corregir excesos, irregularidades o resultados no deseados.",
    price: "530000",
    currency: "COP",
    category: "correctivos",
    durationMinutes: 15,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Mesobotox para acné",
    description: "Tratamiento enfocado en mejorar la calidad de la piel, regular el sebo y mejorar la apariencia del acné.",
    price: "1580000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Barbie Botox",
    description: "Relajación de trapecios para aliviar tensión muscular, estrés y afinar visualmente cuello y hombros.",
    price: "2999000",
    currency: "COP",
    category: "bienestar",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "NCTF — Hidratación de labios",
    description: "Hidratación profunda para labios resecos. Aporta suavidad, luminosidad y mejora la textura sin aumentar volumen.",
    price: "630000",
    currency: "COP",
    category: "labios",
    durationMinutes: 20,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla", "CDMX", "Miami"],
    imageKeys: [],
  },
  {
    name: "Boost Skin Glow",
    description: "Combinación Radiesse + Belotero Revive para potenciar hidratación, luminosidad y calidad de la piel.",
    price: "3420000",
    currency: "COP",
    category: "bioestimuladores",
    durationMinutes: 60,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Korean Face",
    description: "Tratamiento con centella asiática para piel más luminosa, hidratada y saludable. Efecto glow natural.",
    price: "1899000",
    currency: "COP",
    category: "facial",
    durationMinutes: 60,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "PNDR — Esperma de Salmón",
    description: "Avanzado tratamiento de regeneración de piel que mejora luminosidad, textura y calidad desde el interior.",
    price: "800000",
    currency: "COP",
    category: "facial",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
  },
  {
    name: "Micropigmentación de labios",
    description: "Pigmentación con pigmentos orgánicos para dar color a los labios. Incluye primera sesión + retoque + vitamina. Duración hasta 1 año. Solo en Medellín.",
    price: "650000",
    currency: "COP",
    category: "micropigmentación",
    durationMinutes: 90,
    cities: ["Medellín"],
    imageKeys: [],
  },
  {
    name: "Promo — Renovación Facial Masculina",
    description: "Mes de los padres. Botox facial completo para hombre. Por cada referencia que tome la promo, recibes hidratación de labios o facial gratis.",
    price: "1580000",
    currency: "COP",
    category: "promociones",
    durationMinutes: 30,
    cities: ["Medellín", "Bogotá", "Cali", "Bucaramanga", "Barranquilla"],
    imageKeys: [],
    promoLabel: "Mes del Padre",
  },
];

export function getCatalogByCity(city: string): CatalogItem[] {
  const normalized = ciudadNormalize(city);
  return SANTA_MARIA_CATALOG.filter((item) =>
    item.cities.some((c) => ciudadNormalize(c) === normalized)
  );
}

function ciudadNormalize(city: string): string {
  const map: Record<string, string> = {
    medellin: "Medellín",
    "medellín": "Medellín",
    mde: "Medellín",
    bogota: "Bogotá",
    "bogotá": "Bogotá",
    bgt: "Bogotá",
    cali: "Cali",
    bucaramanga: "Bucaramanga",
    bucara: "Bucaramanga",
    barranquilla: "Barranquilla",
    barranca: "Barranquilla",
    "ciudad de méxico": "CDMX",
    cdmx: "CDMX",
    "méxico": "CDMX",
    mexico: "CDMX",
    miami: "Miami",
  };
  const key = city.toLowerCase().trim();
  return map[key] || city;
}

export function formatPrice(price: string, currency: string = "COP"): string {
  const num = parseInt(price, 10);
  if (isNaN(num)) return price;
  const formatted = new Intl.NumberFormat("es-CO").format(num);
  const symbols: Record<string, string> = {
    COP: "$",
    MXN: "$",
    USD: "$",
    EUR: "€",
  };
  return `${symbols[currency] || "$"}${formatted} ${currency}`;
}

export const IMAGE_MANIFEST: Record<string, { service: string; description: string; type: string }> = {
  "image1.jpeg": { service: "price_list", description: "Lista de precios en EUROS (€) — Services & Prices Europa", type: "price_card" },
  "image2.jpeg": { service: "price_list", description: "Lista de precios en PESOS COLOMBIANOS (COP)", type: "price_card" },
  "image3.jpeg": { service: "price_list", description: "Lista de precios en PESOS MEXICANOS (MXN)", type: "price_card" },
  "image4.jpeg": { service: "price_list", description: "Lista de precios en DÓLARES (USD) — EE.UU.", type: "price_card" },
  "image5.jpeg": { service: "Red Lips", description: "Card de Red Lips — $670,000 COP", type: "service_card" },
  "image6.jpeg": { service: "Russian Lips", description: "Card de Russian Lips — precio en MXN", type: "service_card" },
  "image7.jpeg": { service: "Russian Lips", description: "Card de Russian Lips — diseño alternativo", type: "service_card" },
  "image8.jpeg": { service: "Doll Lips", description: "Card de Doll Lips — precio en COP", type: "service_card" },
  "image9.jpeg": { service: "Doll Lips", description: "Card de Doll Lips — precio en COP (alternativo)", type: "service_card" },
  "image10.jpeg": { service: "Red Lips", description: "Card de Red Lips — $6,500 MXN", type: "service_card" },
  "image11.jpeg": { service: "Red Lips", description: "Card de Red Lips — $350 USD", type: "service_card" },
  "image12.jpeg": { service: "Red Lips", description: "Card de Red Lips — 800 €", type: "service_card" },
  "image13.jpeg": { service: "Doll Lips", description: "Card de Doll Lips — vista alternativa", type: "service_card" },
  "image14.jpeg": { service: "Doll Lips", description: "Card de Doll Lips — $899", type: "service_card" },
  "image15.jpeg": { service: "Doll Lips", description: "Card de Doll Lips — 800", type: "service_card" },
  "image16.jpeg": { service: "Full Face — Ácido Hialurónico", description: "Card de Full Face Ácido Hialurónico", type: "service_card" },
  "image17.jpeg": { service: "Marcación mandibular", description: "Card de marcación mandibular", type: "service_card" },
  "image18.jpeg": { service: "Proyección de mentón", description: "Card de proyección de mentón", type: "service_card" },
  "image19.jpeg": { service: "Proyección de pómulos", description: "Card de proyección de pómulos", type: "service_card" },
  "image20.jpeg": { service: "Facial Rejuvenation", description: "Card de rejuvenecimiento facial (inglés)", type: "service_card" },
  "image21.jpeg": { service: "Facial Masculinization", description: "Card de masculinización facial (inglés)", type: "service_card" },
  "image22.jpeg": { service: "Masculinización facial", description: "Card de masculinización facial", type: "service_card" },
  "image23.jpeg": { service: "Full Face — Radiesse", description: "Card de Full Face Radiesse", type: "service_card" },
  "image24.jpeg": { service: "Full Face — Sculptra", description: "Card de Full Face Sculptra", type: "service_card" },
  "image25.jpeg": { service: "Rinomodelación", description: "Card de rinomodelación", type: "service_card" },
  "image26.jpeg": { service: "Barbie Botox", description: "Card de Barbie Botox (trapecios)", type: "service_card" },
  "image27.jpeg": { service: "Korean Face", description: "Card de Korean Face", type: "service_card" },
  "image28.jpeg": { service: "Full Face — Ácido Hialurónico", description: "Card de Full Face Ácido Hialurónico (alternativa)", type: "service_card" },
};
