export { AgentKernel, createAgentKernel } from "./core/agent-kernel.js";
export { ConversationSnapshotBuilder } from "./core/conversation-snapshot.js";
export { classifyIntentStructured } from "./understanding/structured-router.js";
export { safetyPreRoute } from "./understanding/safety-pre-router.js";
export { normalizeInput } from "./understanding/input-normalizer.js";
export { scanRisks } from "./understanding/risk-scanner.js";
export { evaluatePolicy, enforceClinicalSafety } from "./policy/policy-engine.js";
export { scanPromptInjection } from "./policy/prompt-injection.js";
export { evaluateClinicalSafety } from "./policy/clinical-safety.js";
export { detectPII, sanitizeText, summarizeForTrace, validateDataCollection } from "./policy/privacy-safety.js";
export { createEmptyMemory, memoryValue, mergeMemoryValues } from "./memory/memory-types.js";
export { extractMemoryFromMessage, deriveFunnelStage, markDataProvided } from "./memory/memory-manager.js";
export { createMemoryRepository } from "./memory/memory-repository.js";
export type { MemoryRepository } from "./memory/memory-repository.js";
export { MemoryService } from "./memory/memory-service.js";
export type { MemoryUserContext, DataCollectionResult } from "./memory/memory-service.js";
export { FlowAdapter } from "./adapter/flow-adapter.js";
export type { FlowAdapterResult } from "./adapter/flow-adapter.js";
export { createPlan } from "./planning/conversation-planner.js";
export { detectObjection, getObjectionResponse } from "./planning/objection-handler.js";
export { selectTone } from "./response/tone-adapter.js";
export { composeResponse } from "./response/response-composer.js";
export { criticize, maskPII, maskCedula, maskPhone, maskEmail } from "./response/response-critic.js";
export type { CriticAction, ResponseCriticIssue, ResponseCriticResult, CriticInput } from "./response/response-critic.js";

export type { ClinicalSafetyDecision } from "./policy/clinical-safety.js";
export type { PIIItem, PrivacyCheckResult } from "./policy/privacy-safety.js";
export type { PatientConversationMemory } from "./memory/memory-types.js";
export type { ObjectionInfo } from "./planning/objection-handler.js";
export type { ToneDecision } from "./response/tone-adapter.js";
export type { ComposerInput, ComposerOutput } from "./response/response-composer.js";
export type { KernelProviders } from "./core/agent-kernel.js";
export type { ConversationSnapshot } from "./core/conversation-snapshot.js";
export type { NormalizedInput } from "./understanding/input-normalizer.js";
export type { PromptInjectionScan } from "./policy/prompt-injection.js";

export { AGENT_INTENTS } from "./types/agent-intent.js";
export type { AgentIntent, ExtractedEntities, RouterDecision } from "./types/agent-intent.js";
export type { AgentKernelInput, AgentKernelOutput, MemoryUpdate, AgentEvent, AgentEventType } from "./types/agent-kernel.js";
export type { DecisionTrace, SafetyLevel, ResponseStrategy, RiskFlags, PolicyDecision } from "./types/decision-trace.js";
export type { ResponseContract, ToneProfile } from "./types/response-contract.js";
export type { FunnelStage, NextBestAction, ConversationPlan } from "./types/funnel.js";
